### ISSUE TITLE
App Manager keeps crashing if I select anything 

### ISSUE THREAD

**Issue by gituser823** [MuntashirAkon/AppManager#1316]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I can open the app just fine.

But selecting any App crashes the AppManager

### To Reproduce

1. Start the app
2. Click on any app

### Expected behavior

The menu for the selected app should show up.

### Screenshots

-

### Logs

java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.details.AppDetailsActivity}: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.details.AppDetailsViewModel
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3946)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4126)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:108)
    at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:195)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:157)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:90)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2544)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8501)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
 Caused by: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.details.AppDetailsViewModel
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:320)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:96)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:87)
   at android.app.Activity.performCreate(Activity.java:8767)
   at android.app.Activity.performCreate(Activity.java:8745)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1519)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3928)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4126)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:108)
   at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:195)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:157)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:90)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2544)
   at android.os.Handler.dispatchMessage(Handler.java:107)
   at android.os.Looper.loopOnce(Looper.java:232)
   at android.os.Looper.loop(Looper.java:317)
   at android.app.ActivityThread.main(ActivityThread.java:8501)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
 Caused by: java.lang.reflect.InvocationTargetException
   at java.lang.reflect.Constructor.newInstance0(Native Method)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:312)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:96)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:87)
   at android.app.Activity.performCreate(Activity.java:8767)
   at android.app.Activity.performCreate(Activity.java:8745)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1519)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3928)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4126)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:108)
   at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:195)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:157)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:90)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2544)
   at android.os.Handler.dispatchMessage(Handler.java:107)
   at android.os.Looper.loopOnce(Looper.java:232)
   at android.os.Looper.loop(Looper.java:317)
   at android.app.ActivityThread.main(ActivityThread.java:8501)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
 Caused by: java.lang.NoSuchMethodError: No interface method grantRuntimePermission(Ljava/lang/String;Ljava/lang/String;I)V in class Landroid/permission/IPermissionManager; or its super classes (declaration of 'android.permission.IPermissionManager' appears in /system/framework/framework.jar!classes3.dex)
   at io.github.muntashirakon.AppManager.compat.PermissionCompat.grantPermission(PermissionCompat.java:333)
   at io.github.muntashirakon.AppManager.compat.AppOpsManagerCompat.<init>(AppOpsManagerCompat.java:629)
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.<init>(AppDetailsViewModel.java:668)
   at java.lang.reflect.Constructor.newInstance0(Native Method)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:312)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:96)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:87)
   at android.app.Activity.performCreate(Activity.java:8767)
   at android.app.Activity.performCreate(Activity.java:8745)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1519)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3928)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4126)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:108)
   at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:195)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:157)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:90)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2544)
   at android.os.Handler.dispatchMessage(Handler.java:107)
   at android.os.Looper.loopOnce(Looper.java:232)
   at android.os.Looper.loop(Looper.java:317)
   at android.app.ActivityThread.main(ActivityThread.java:8501)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

Device Info:
App version: 3.1.4
App version code: 427
Android build version: 11445699
Android release version: 14
Android SDK version: 34
Android build ID: AP1A.240305.019.A1
Device brand: google
Device manufacturer: Google
Device name: shiba
Device model: Pixel 8
Device product name: shiba
Device hardware name: shiba
ABIs: [arm64-v8a]
ABIs (32bit): []
ABIs (64bit): [arm64-v8a]
System language: de-DE
In-App Language: auto
Mode: auto
Inferred Mode: root

### Device info

- Device: Google Pixel 8
- OS Version: Android 14
- App Manager Version: 3.1.4
- Mode: Root

**Comment by craigacgomez** [comment]
@gituser823, You are not running the latest version. This has been fixed in version 3.1.5

**Comment by gituser823** [comment]
I installed it from F-Droid.

I just checked again and F-Droid still shows version 3.1.4

Why wont it show v 3.1.5 in F-Droid?

**Comment by MuntashirAkon** [comment]
> Why wont it show v 3.1.5 in F-Droid?

It takes a few days to a month for F-Droid to pick up, build and publish a new release. We do not have any control over F-Droid build cycle. So, you need to wait until F-Droid publishes the release.

**Comment by MuntashirAkon** [comment]
Duplicate of #1301
