### ISSUE TITLE
Blank main page on a multi-user environment in Android 15

### ISSUE THREAD

**Issue by amijafi** [MuntashirAkon/AppManager#1521]
### Please check before submitting an issue

- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I have this issue since latest 2 betas and recent version4 release , the app stucks on first-start blank page with a search bar motion trying to get the packages list but it never ends and doesn't stop searching or showing any app name or any error , just blank page with endless search . I've also have tried full uninstall then reinstall and clear data . I'm on S22ultra oneui 6.1 , latest v4 release

### To Reproduce

Just open the app

### Expected behavior

Show app list after some time 

### Screenshots

<details>

<summary>Screenshot</summary>

![Image](https://github.com/user-attachments/assets/a20d7fb9-04c8-4745-b963-81cef7764e95)
</details>

### Device info

- Device: s22ultra
- OS Version: android 15 oneui 6.1
- App Manager Version: 4
- Mode: NonRoot

**Comment by Doc-4** [comment]
I have this problem as well, only showed up after the update. I also have a private space.

**Comment by MuntashirAkon** [comment]
This is interesting. The users are reported correctly by the system, but attempting to fetch anything for the other users throws a security exception. I need to take a look at the relevant source to see if additional permissions are needed.

**Comment by Anonymous2716** [comment]
I have another but maybe related issue. the app installer loads infinitely like this. noticed after upgrading to Android 15 . and this happens on the previous version of AppManager from fdroid.

**Comment by MuntashirAkon** [comment]
Can anybody confirm if the issue has been fixed? I've added a new permission to access the so called "Private space" (or equivalent in Samsung) in v4.0.1.

**Comment by Doc-4** [comment]
Nope, still broken on Pixel 8 Pro Android 15 (GrapheneOS)

**Comment by MuntashirAkon** [comment]
I have only checked private space. Work profile is accessed using the Launcher APIs which may not work in Android 15 (basically, a privacy leak found by an App Manager user).

**Comment by amijafi** [comment]
Not for me , samsung s22 oneui 6.1 android 14

**Comment by MuntashirAkon** [comment]
Fixed in 04f202b320d4979f3258aa2387a38599645d132b

**Comment by pixincreate** [comment]
this issue is still reproducible in android 17 (at least on GrapheneOS).

multi user setup exists - private space, work profile,

**Comment by MuntashirAkon** [comment]
> this issue is still reproducible in android 17 (at least on GrapheneOS).

Android 17 is currently not supported. See #1948
