### ISSUE TITLE
Scanner not blocking enough ads

### ISSUE THREAD

**Issue by UltraBlackLinux** [MuntashirAkon/AppManager#168]
**Describe the existing feature/documentation**
So a while back classyshark got replaced by scanner, but I have since then had some problems with scanner.

**Describe your problem(s)*
Even though *all* trackers have been blocked, there are still ads showing up everywhere. What I noticed is, that all problem apps have the 9 TT[...] activities - so now what?  

*Notes*
Please tell me, where I can find scanner - it isn't a thing you can search for - you just get spammed with bad antiviruses if I try to find it...

**Comment by MuntashirAkon** [comment]
This isn't an issue with AM but with Exodus. They've made some changes of late which are making me reconsider the options. I've opened an issue on their ETIP repo but haven't got any reply yet.

> What I noticed is, that all problem apps have the 9 TT[...] activities - so now what?

What's this?

**Comment by MuntashirAkon** [comment]
I've added a temporary fix in e5c11744.

**Comment by UltraBlackLinux** [comment]
@MuntashirAkon 
> What's this?
TT delecate act.
TT Fullscreen express act.
TT Fullscreen Vid. act.
TT landing Page act.
TT playable landing Page act.
TT reward express Vid. act.
TT reward vid. act.
TT vid. Landing page act.
TT Website act.
-> bytedance

**Comment by MuntashirAkon** [comment]
Could you share an example app so that I can test?

**Comment by UltraBlackLinux** [comment]
@MuntashirAkon it's crazy that I am so bored that I even play this dumb shitapp:
https://play.google.com/store/apps/details?id=com.pixelbox.roofrails

**Comment by MuntashirAkon** [comment]
> @MuntashirAkon it's crazy that I am so bored that I even play this dumb shitapp:
> https://play.google.com/store/apps/details?id=com.pixelbox.roofrails

Thanks. It seems `com.bytedance.sdk.openadsdk.` is missing from Exodus (it was never added). I'll add it in my custom ads list.

**Comment by MuntashirAkon** [comment]
Fixed via ff40be6c

**Comment by MuntashirAkon** [comment]
> it's crazy that I am so bored that I even play this dumb shitapp

I've never seen an app with this many advertising components!

**Comment by UltraBlackLinux** [comment]
@MuntashirAkon The problem still persists with another app https://play.google.com/store/apps/details?id=com.h8games.targetplanets
Another trashapp :/

**Comment by MuntashirAkon** [comment]
> The problem still persists with another app https://play.google.com/store/apps/details?id=com.h8games.targetplanets

Could you indicate the problematic components/classes?

**Comment by UltraBlackLinux** [comment]
@MuntashirAkon so I tried for about an hour now, and did all the stuff over and over again, and I am tired of it, please try it yourself... :(

**Comment by MuntashirAkon** [comment]
I haven't found any new ad/tracker in the app other than `com.bytedance.sdk.openadsdk.` which is already added in ff40be6.

**Comment by pnu-s** [comment]
> Thanks. It seems `com.bytedance.sdk.openadsdk.` is missing from Exodus (it was never added). I'll add it in my custom ads list.

Hello there!

Exodus contributor here. If they are some missing trackers from exodus, feel free to create new profiles on https://github.com/Exodus-Privacy/etip/ Even if that takes probably more time than adding it to your custom list, it can benefit to everyone :tada:

**Comment by MuntashirAkon** [comment]
> If they are some missing trackers from exodus, feel free to create new profiles on https://github.com/Exodus-Privacy/etip/ Even if that takes probably more time than adding it to your custom list, it can benefit to everyone 🎉

Thanks for the reply! I wish I could contribute to the Exodus project but as you have guessed already: I don't get enough time to contribute to other projects as I have to maintain at least four projects and a few libraries which take most if not all of my free time. But yes, I can make a report specifying the signatures like I did before. But you should create some issue templates as they make things a lot easier.

**Comment by pnu-s** [comment]
Sure, I get it :)

To be honest, we basically created ETIP to get away from the "people create issue to report new tracker" situation. But we probably have still a lot of work to simplify the creation of tracker profiles on ETIP.

**Comment by MuntashirAkon** [comment]
> But we probably have still a lot of work to simplify the creation of tracker profiles on ETIP.

Yeah, it's very difficult to create and verify new trackers. I wish more people would contribute to ETIP instead of just complaining about it.
