### ISSUE TITLE
Crash while trying to disable background

### ISSUE THREAD

**Issue by RickyM7** [MuntashirAkon/AppManager#212]
**To Reproduce**
Steps to reproduce the behaviour:
1. Select any app in AM
2. Open the batch operations menu
3. Click "Disable Background" and confirm as soon as the confirmation dialog appears

**Crash logs**
java.lang.SecurityException: grantRuntimePermission: Neither user 11957 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
    at android.os.Parcel.readException(Parcel.java:1715)
    at android.os.Parcel.readException(Parcel.java:1668)
    at android.content.pm.IPackageManager$Stub$Proxy.grantRuntimePermission(IPackageManager.java:2952)
    at io.github.muntashirakon.AppManager.servermanager.PackageManagerCompat.grantPermission(PackageManagerCompat.java:100)
    at io.github.muntashirakon.AppManager.appops.AppOpsService.<init>(AppOpsService.java:49)
    at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.opDisableBackground(BatchOpsManager.java:327)
    at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:189)
    at io.github.muntashirakon.AppManager.batchops.BatchOpsService.onHandleIntent(BatchOpsService.java:210)
    at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:28)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:165)
    at android.os.HandlerThread.run(HandlerThread.java:61)

Device Info:
App version: 2.5.22-DEBUG
App version code: 378
Android build version: V11.0.2.0.NCFMIXM
Android release version: 7.0
Android SDK version: 24
Android build ID: AL1512-mido-build-20191107001817
Device brand: xiaomi
Device manufacturer: Xiaomi
Device name: mido
Device model: Redmi Note 4
Device product name: mido
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: pt-BR
In-App Language: auto

**Device info**
 - Device: Redmi Note 4
 - OS Version: MIUI 11 (Android 7.0)
 - App Manager Version: v2.5.22-DEBUG#700
 - Mode: no-root

**Comment by MuntashirAkon** [comment]
Fixed in 054ef9ea.

**Comment by RickyM7** [comment]
@MuntashirAkon This still continues (tested up to v2.5.22-DEBUG#708).

java.lang.SecurityException: grantRuntimePermission: Neither user 11965 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
    at android.os.Parcel.readException(Parcel.java:1715)
    at android.os.Parcel.readException(Parcel.java:1668)
    at android.content.pm.IPackageManager$Stub$Proxy.grantRuntimePermission(IPackageManager.java:2952)
    at io.github.muntashirakon.AppManager.servermanager.PackageManagerCompat.grantPermission(PackageManagerCompat.java:105)
    at io.github.muntashirakon.AppManager.appops.AppOpsService.<init>(AppOpsService.java:51)
    at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.opDisableBackground(BatchOpsManager.java:328)
    at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.performOp(BatchOpsManager.java:188)
    at io.github.muntashirakon.AppManager.batchops.BatchOpsService.onHandleIntent(BatchOpsService.java:210)
    at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:28)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:165)
    at android.os.HandlerThread.run(HandlerThread.java:61)

Device Info:
App version: 2.5.22-DEBUG
App version code: 378
Android build version: V11.0.2.0.NCFMIXM
Android release version: 7.0
Android SDK version: 24
Android build ID: AL1512-mido-build-20191107001817
Device brand: xiaomi
Device manufacturer: Xiaomi
Device name: mido
Device model: Redmi Note 4
Device product name: mido
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: pt-BR
In-App Language: auto

**Comment by MuntashirAkon** [comment]
Oops, I've made a mistake in the logic. Should be fixed in dbcc0b5f.

**Comment by RickyM7** [comment]
> Oops, I've made a mistake in the logic. Should be fixed in dbcc0b5.

Now it has been fixed, thank you.
