### ISSUE TITLE
Applying blocking rules fails once if app's component list changed

### ISSUE THREAD

**Issue by SkRiMiX** [MuntashirAkon/AppManager#255]
**Describe the bug**
Applying blocking rules fails on first attempt if component list changed after target app was updated and old blocking rules were applied prior to update.

**To Reproduce**
1. Install old version of Apple Music (I tested with v3.3.0).
2. Use "Block trackers" on the app.
3. Update Apple Music to latest version (v3.4.5).
4. a) Use "Block trackers" again. OR b) Toggle blocking of a component.
5. a) "Could not block trackers" notification appears. OR b) AppManager crashes.
6. Try blocking again.
7. Rules apply successfully.

**Expected behavior**
Applying rules succeeds on first attempt after component list changed.

**Screenshots**
None.

**Crash logs**
[Link](https://del.dog/ghibinewec.txt)

**Device info**
 - Device: Xiaomi Redmi Note 8 Pro
 - OS Version: Android 11
 - App Manager Version: v2.5.23-DEBUG (380)
 - Mode: root

**Additional context**
This issue was happening constantly for affected apps and was partially fixed. Now it happens only once for every affected app.

**Comment by MuntashirAkon** [comment]
Fixed via 85fdc753

**Comment by SkRiMiX** [comment]
Seems like it's not completely fixed. On latest builds I've found fail conditions to be: AM is running when affected app is updated and app list has not been manually refreshed by user. 
I did a little bit of debugging and found that on rules validation components list still contained old component, meaning it wasn't updated.

**Comment by MuntashirAkon** [comment]
> AM is running when affected app is updated and app list has not been manually refreshed by user.

Yes, but this only happens if the App Details page for the app is left opened or if it was the last app to be opened, no? It should work fine in other situations.

---
_I was meaning to write some integration tests but it takes a lot of time to run these tests as my laptop has very poor specs 😞 ._

**Comment by SkRiMiX** [comment]
Yes, if I refresh app list or open another app's page it works correctly, so conditions are quite specific here. 
And one thing I noticed is that AM crashes if I manually toggle some component in this case. Maybe catch the corresponding exception too?

**Comment by MuntashirAkon** [comment]
> Maybe catch the corresponding exception too?

Yeah, but that'd solve the problem without solving the underlying problems (xy problem). Not something I would prefer.

**Comment by SkRiMiX** [comment]
Of course, I didn't mean it as a workaround for this issue. I mean in situations like this shouldn't such exceptions be caught? Unless crash is more preferable here to make problems occuring more apparent. I don't know, I have no knowledge here.

**Comment by MuntashirAkon** [comment]
In general, runtime exceptions are never caught because they are expected never to occur (except in a few places such as checking whether a string is a number). When it deems necessary to catch such exceptions, it almost always means that the situation is not handled properly and there are better alternatives. In this case, there's definitely other alternatives to consider. I hope this makes things clear.

**Comment by MuntashirAkon** [comment]
Fixed via 8558edc1 and 4628362c.
