### ISSUE TITLE
AM randomly freezing after launch.

### ISSUE THREAD

**Issue by tommynok** [MuntashirAkon/AppManager#280]
Alogrhythm -
start AM - main window - " Initialization " - black window. AM remains in this state for a long time (waiting 3-5 minutes).
Only closing AM helps.
Device Lenovo P1, OS MM
AppManager_v2.5.24-DEBUG#881
Root mode
[logs-2021-02-09-04-59-10.zip](https://github.com/MuntashirAkon/AppManager/files/5948710/logs-2021-02-09-04-59-10.zip)
[logs-2021-02-09-04-58-30.zip](https://github.com/MuntashirAkon/AppManager/files/5948711/logs-2021-02-09-04-58-30.zip)

**Comment by MuntashirAkon** [comment]
Should be fixed in ad7a3abe

**Comment by tommynok** [comment]
> Should be fixed in [ad7a3ab](https://github.com/MuntashirAkon/AppManager/commit/ad7a3abeb8c250dd42e0bb05b8122a2df6d00c26)

Still face this problem after clean install debug build v2.5.24-DEBUG#882
[logs-2021-02-09-16-18-53.zip](https://github.com/MuntashirAkon/AppManager/files/5951621/logs-2021-02-09-16-18-53.zip)
[logs-2021-02-09-16-18-23.zip](https://github.com/MuntashirAkon/AppManager/files/5951622/logs-2021-02-09-16-18-23.zip)
[2021-02-09_161603_logcat.zip](https://github.com/MuntashirAkon/AppManager/files/5951623/2021-02-09_161603_logcat.zip)

**Comment by MuntashirAkon** [comment]
Check 4eb596b8

**Comment by tommynok** [comment]
> Check [4eb596b](https://github.com/MuntashirAkon/AppManager/commit/4eb596b8026d4cc5bd90f29f64a35004f0291551)

There seems to be no change.
Sometimes AM loads the home page instantly.
But sometimes I have to wait 2-3 minutes for the main AM window to appear. And during these 2-3 minutes I see a dark screen.
I cannot understand the pattern of this behavior (
[logs-2021-02-15-15-42-18.zip](https://github.com/MuntashirAkon/AppManager/files/5981773/logs-2021-02-15-15-42-18.zip)
[logs-2021-02-15-15-41-37.zip](https://github.com/MuntashirAkon/AppManager/files/5981774/logs-2021-02-15-15-41-37.zip)
[2021-02-15_153833_logcat.txt](https://github.com/MuntashirAkon/AppManager/files/5981775/2021-02-15_153833_logcat.txt)

**Comment by tommynok** [comment]
Upd - AppManager_v2.5.24-DEBUG#905
[logs-2021-02-18-15-13-16.zip](https://github.com/MuntashirAkon/AppManager/files/6005228/logs-2021-02-18-15-13-16.zip)
[logs-2021-02-18-15-12-36.zip](https://github.com/MuntashirAkon/AppManager/files/6005229/logs-2021-02-18-15-12-36.zip)
[logs-2021-02-18-15-11-48.zip](https://github.com/MuntashirAkon/AppManager/files/6005230/logs-2021-02-18-15-11-48.zip)

**Comment by MuntashirAkon** [comment]
Fixed in 6f4f932b.
