### ISSUE TITLE
App list is not complete

### ISSUE THREAD

**Issue by MPeti1** [MuntashirAkon/AppManager#298]
Note: it seems to be the same as #140. Most of the following is copied from that issue.

**Describe the bug**
On the main menu (where the installed apps are listed) there are certain apps that I can't find.
One such app is the Reddit client named Boost (com.rubenmayayo.reddit).

**To Reproduce**
Steps to reproduce the behaviour:

0. Install the Boost app
1. Open App Manager
2. Scroll to the apps that start with the letter B, or search for Boost
3. The mentioned app is not there

**Expected behavior**
The app should be listed there

**Device info**
 - Device: Xiaomi Redmi 3S
 - OS Version: MIUI 8, Android 6 (SDK23)
 - App Manager Version: 2.5.23-PRE (381) and also 2.5.24-DEBUG (382)
 - Mode: root in pre-release, no-root in debug 

**Additional context**
It seems like the same apps are missing as in the mentioned issue, so it's probably the same problem.
Also, I noticed that if I search for "simple", the ordering is now a bit different than [here](https://github.com/MuntashirAkon/AppManager/issues/140#issuecomment-720471093): `Simple` is listed earlier than `Simple System Monitor`, probably because it's shorter. Not sure if it's intentional, just wanted to mention.

**Comment by MuntashirAkon** [comment]
> * OS Version: MIUI 8

By OS version, I meant Android OS, not some distro.

Was this reproducible in other versions like v2.5.22 or earlier? You also haven't provided any logcat output since it's not reproducible on my device (Android 10).

**Comment by MPeti1** [comment]
> By OS version, I meant Android OS, not some distro.

Fixed

> Was this reproducible in other versions like v2.5.22 or earlier?

I've tried out now a couple of versions, but in all of them the same apps were missing, including in 2.5.19, which was [working before](https://github.com/MuntashirAkon/AppManager/issues/140#issuecomment-742869072).

Logs from debug #929: https://gist.github.com/MPeti1/74931f9b6e87e0b4ab8b5ebeeecef403

Probably it's just my buggy OS again, at this point I'm not even sure if I should leave this issue open. If I'm not mistaken, line 38-39 in the log says it all..

**Comment by MuntashirAkon** [comment]
> Logs from debug #929: https://gist.github.com/MPeti1/74931f9b6e87e0b4ab8b5ebeeecef403

You seem to have filtered logs for app manager only. As I mentioned in the previous issue, this is an OS bug and I've to see system logs in order to find the issue.

**Comment by MPeti1** [comment]
I've added a [second file](https://gist.github.com/MPeti1/74931f9b6e87e0b4ab8b5ebeeecef403#file-gistfile2-txt) with unfiltered log to gist. The log starts when I started the app (from being killed first), and ends after I type in "boo" to see if Boost for Reddit is in the list.

**Comment by MuntashirAkon** [comment]
> I've added a [second file](https://gist.github.com/MPeti1/74931f9b6e87e0b4ab8b5ebeeecef403#file-gistfile2-txt) with unfiltered log to gist. The log starts when I started the app (from being killed first), and ends after I type in "boo" to see if Boost for Reddit is in the list.

```
ParceledListSlice: Failure retrieving array; only received 259 of 468
android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:506)
        at android.content.pm.ParceledListSlice.<init>(ParceledListSlice.java:97)
        at android.content.pm.ParceledListSlice.<init>(ParceledListSlice.java:41)
        at android.content.pm.ParceledListSlice$2.createFromParcel(ParceledListSlice.java:200)
        at android.content.pm.ParceledListSlice$2.createFromParcel(ParceledListSlice.java:198)
        at android.content.pm.IPackageManager$Stub$Proxy.getInstalledPackages(IPackageManager.java:3221)
        at io.github.muntashirakon.AppManager.servermanager.PackageManagerCompat.getInstalledPackages(PackageManagerCompat.java:70)
        at io.github.muntashirakon.AppManager.utils.PackageUtils.updateInstalledOrBackedUpApplications(PackageUtils.java:200)
        at io.github.muntashirakon.AppManager.utils.PackageUtils.lambda$getInstalledOrBackedUpApplicationsFromDb$0(PackageUtils.java:128)
        at io.github.muntashirakon.AppManager.utils.-$$Lambda$PackageUtils$_ntGZecZygOpLPZuUERapBd5p-Q.run(lambda)
        at java.lang.Thread.run(Thread.java:818)
```

For some reason the system is failing to return info for all apps. Have you applied any system patch or installed Xposed?

**Comment by MPeti1** [comment]
Xposed is installed, but I don't have any modules that should touch the PackageManager or the IPC system.
Also, if I disable Xposed in it's manager app and reboot (so no modules are loaded) I get the same error, except that it now received 248 of 457 (I've removed a few apps since the log), but the difference is still 209.

**Comment by MPeti1** [comment]
Is it known how an array receiving failure like this looks like? As in, is the array continous, and all the 209 entries are missing from the end of it, or are there gaps in the array?

**Comment by MuntashirAkon** [comment]
> Is it known how an array receiving failure like this looks like?

AOSP has created `ParceledListSlice` because the regular `java.util.List` doesn't work properly for large arrays when communicating via IPC using Binder. So, I'm not sure why this results in missing exactly 209 apps in particular.

**Comment by MuntashirAkon** [comment]
In @2011's case, the difference is 176.

**Comment by MuntashirAkon** [comment]
@MPeti1: Can you try the latest debug build? I've to make sure that it's not a result of the fallback method that I've implemented (it shouldn't be). Make sure to restart after installing the build.

**Comment by MPeti1** [comment]
Apps are still missing in 2.7.0-1200, so that shouldn't be a problem

**Comment by MPeti1** [comment]
Well, 5 apps is not much. But I think I got an idea. Would it help if I found out somehow how is the settings app able to get a full list of the installed apps?

**Comment by MuntashirAkon** [comment]
> Well, 5 apps is not much. But I think I got an idea. Would it help if I found out somehow how is the settings app able to get a full list of the installed apps?

No, it wouldn't. Settings doesn't need to fetch as much information as AM does. The limit, in this case, is the amount of data that can be transferred over IPC (Binder) and the `ParceledListSlice` is supposed to fix that which it isn't, possibly due to buggy implementation in the OS. We have other Android 6 users who never reported it, testers haven't faced the issue either. So, it's likely that a particular patch is problematic, similar to #159. There might be a (slower) way to fix this issue which I'll work on later.

**Comment by MuntashirAkon** [comment]
@MPeti1: Can you try an old release such as [v2.0.0](https://github.com/MuntashirAkon/AppManager/releases/tag/v2.0.0) (the first release of AM)?

**Comment by MPeti1** [comment]
With the linked v2.0.0 release I can see the missing apps:
|||
|:-:|:-:|
|![image](https://user-images.githubusercontent.com/9215491/116871641-1c534d00-ac04-11eb-8651-b36b7d50a555.png)|!![image](https://user-images.githubusercontent.com/9215491/116871735-4278ed00-ac04-11eb-9aac-5cf31772c12e.png)

Also with this version I don't see a ParceledListSlice warning in the logcat

**Comment by MuntashirAkon** [comment]
> Also with this version I don't see a ParceledListSlice warning in the logcat

This is definitely due to the limit to the amount of data that can be passed through Binder.

**Comment by MuntashirAkon** [comment]
OK, this could be exclusive to Android 6, maybe a certain patch level since the testers with Android 6 have never reported this issue. @2011 and @MPeti1: can you share the exact Android version with patch level? I'll add workaround for the specified patch level only as the method of retrieving packages won't be very efficient like in the past.

**Comment by 2011** [comment]
I have (from the About tablet page):

Android version: 6.0.1

LineageOS version: 13.0.20180211-NIGHTLY-espressowifi

LineageOS API level: Fig (6) [I have no idea what that means]

Android security patch level: January 1, 2018

Kernel version: 3.0.101-g176096d, jenkins@iktinos.acc.umu.se #1

**Comment by bfabiszewski** [comment]
I have same issue.

Android version: 6.0
Android security patch level: December 5, 2016
Kernel version: 3.18.19

**Comment by MPeti1** [comment]
Mine is 2017-04-01

**Comment by MuntashirAkon** [comment]
Should be fixed in 09195323.

**Comment by bfabiszewski** [comment]
> Should be fixed in 0919532.

Trying debug build I encountered following issue with this debug build: `PackageUtils: android.os.RemoteException: com.xxx.xxx not found` (I anonymized package name). And the list was empty. 
After uninstalling the package everything started working. The full list was loaded.

Now, after uninstalling the troublesome package, also latest stable version started working. 
So I don't know if the debug build fixed anything, but it definitelly helped to find that there was a problem with particular package. In stable build previously I didn't get this error with PackageUtils, just `ParceledListSlice: Failure retrieving array`.


```
05-09 12:32:14.862  4151  4160 D IPC     : transact: uid=10137, descriptor=android.content.pm.IPackageManager, code=3
05-09 12:32:14.864  4151  4160 D IPC     : transact: uid=10137, descriptor=android.content.pm.IPackageManager, code=3
05-09 12:32:14.869  4151  4160 D IPC     : transact: uid=10137, descriptor=android.content.pm.IPackageManager, code=3
05-09 12:32:14.880  4151  4160 D IPC     : transact: uid=10137, descriptor=android.content.pm.IPackageManager, code=3
05-09 12:32:14.888  4151  4160 D IPC     : transact: uid=10137, descriptor=android.content.pm.IPackageManager, code=3
05-09 12:32:14.891  4151  4160 D IPC     : transact: uid=10137, descriptor=android.content.pm.IPackageManager, code=3
05-09 12:32:14.895  4151  4160 D IPC     : transact: uid=10137, descriptor=android.content.pm.IPackageManager, code=3
05-09 12:32:14.899  4151  4160 D IPC     : transact: uid=10137, descriptor=android.content.pm.IPackageManager, code=3
05-09 12:32:14.904  4151  4160 D IPC     : transact: uid=10137, descriptor=android.content.pm.IPackageManager, code=3
05-09 12:32:14.906  4151  4160 D IPC     : transact: uid=10137, descriptor=android.content.pm.IPackageManager, code=3
05-09 12:32:14.908  4151  4160 D IPC     : transact: uid=10137, descriptor=android.content.pm.IPackageManager, code=3
05-09 12:32:14.913  4151  4160 D IPC     : transact: uid=10137, descriptor=android.content.pm.IPackageManager, code=3
05-09 12:32:14.918  4151  4160 D IPC     : transact: uid=10137, descriptor=android.content.pm.IPackageManager, code=3
05-09 12:32:14.988  4151  4160 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 132)
05-09 12:32:14.989  4151  4160 E JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
05-09 12:32:14.989  4151  4160 E JavaBinder: java.lang.RuntimeException: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
05-09 12:32:14.989  4151  4160 E JavaBinder: 	at android.os.Parcel.writeException(Parcel.java:1499)
05-09 12:32:14.989  4151  4160 E JavaBinder: 	at android.os.Binder.execTransact(Binder.java:464)
05-09 12:32:14.989  4151  4160 E JavaBinder: Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
05-09 12:32:14.989  4151  4160 E JavaBinder: 	at android.os.BinderProxy.transactNative(Native Method)
05-09 12:32:14.989  4151  4160 E JavaBinder: 	at android.os.BinderProxy.transact(Binder.java:511)
05-09 12:32:14.989  4151  4160 E JavaBinder: 	at io.github.muntashirakon.AppManager.ipc.AMService$IAMServiceImpl.transactRemote(AMService.java:147)
05-09 12:32:14.989  4151  4160 E JavaBinder: 	at io.github.muntashirakon.AppManager.ipc.AMService$IAMServiceImpl.onTransact(AMService.java:121)
05-09 12:32:14.989  4151  4160 E JavaBinder: 	at android.os.Binder.execTransact(Binder.java:458)
05-09 12:32:14.991  4991  5091 E PackageUtils: Could not retrieve package info list for user 0
05-09 12:32:14.991  4991  5091 E PackageUtils: android.os.RemoteException: com.xxx.xxx not found.
05-09 12:32:14.991  4991  5091 E PackageUtils: 	at io.github.muntashirakon.AppManager.servermanager.PackageManagerCompat.getInstalledPackages(PackageManagerCompat.java:93)
05-09 12:32:14.991  4991  5091 E PackageUtils: 	at io.github.muntashirakon.AppManager.utils.PackageUtils.updateInstalledOrBackedUpApplications(PackageUtils.java:258)
05-09 12:32:14.991  4991  5091 E PackageUtils: 	at io.github.muntashirakon.AppManager.utils.PackageUtils.getInstalledOrBackedUpApplicationsFromDb(PackageUtils.java:166)
05-09 12:32:14.991  4991  5091 E PackageUtils: 	at io.github.muntashirakon.AppManager.main.MainViewModel.lambda$loadApplicationItems$2$MainViewModel(MainViewModel.java:266)
05-09 12:32:14.991  4991  5091 E PackageUtils: 	at io.github.muntashirakon.AppManager.main.-$$Lambda$MainViewModel$GRBvAab9qfeXsa_mTxGQ7idH9GI.run(lambda)
05-09 12:32:14.991  4991  5091 E PackageUtils: 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by MPeti1** [comment]
The list is empty for me too, I'll check the logs soon

**Comment by MuntashirAkon** [comment]
> Now, after uninstalling the troublesome package, also latest stable version started working.

Try the same (with the problematic app installed) but without root. It's easier to debug that way. There could be two reasons:
1. The amount of data returned by the app has is much larger than the parcel size limit (there's no fix for this)
2. PackageManager has a request limit which has been surpassed (I've already added a fix but that might not be working correctly)

It's possible to simply ignore the problematic app but that's not a good solution.

**Comment by MPeti1** [comment]
I almost said it's also good to know which app is the offender and breaks the packagemanager, because at least I know which one to get rid of. Well, I'm not sure I can get rid of `com.google.android.gms` :D

```
05-09 13:47:07.587 11666-11707/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 140)
05-09 13:47:07.588 11666-11707/? E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    java.lang.RuntimeException: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.Parcel.writeException(Parcel.java:1520)
        at android.os.Binder.execTransact(Binder.java:459)
     Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:506)
        at io.github.muntashirakon.AppManager.ipc.AMService$IAMServiceImpl.transactRemote(AMService.java:147)
        at io.github.muntashirakon.AppManager.ipc.AMService$IAMServiceImpl.onTransact(AMService.java:121)
        at android.os.Binder.execTransact(Binder.java:453)
05-09 13:47:07.590 13258-13360/io.github.muntashirakon.AppManager.debug E/PackageUtils: Could not retrieve package info list for user 0
    android.os.RemoteException: com.google.android.gms not found.
        at io.github.muntashirakon.AppManager.servermanager.PackageManagerCompat.getInstalledPackages(PackageManagerCompat.java:93)
        at io.github.muntashirakon.AppManager.utils.PackageUtils.updateInstalledOrBackedUpApplications(PackageUtils.java:258)
        at io.github.muntashirakon.AppManager.utils.PackageUtils.getInstalledOrBackedUpApplicationsFromDb(PackageUtils.java:166)
        at io.github.muntashirakon.AppManager.main.MainViewModel.lambda$loadApplicationItems$2$MainViewModel(MainViewModel.java:266)
        at io.github.muntashirakon.AppManager.main.-$$Lambda$MainViewModel$GRBvAab9qfeXsa_mTxGQ7idH9GI.run(lambda)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by MPeti1** [comment]
with 'no root' mode I get this:
```
05-09 14:22:23.965 14988-15020/io.github.muntashirakon.AppManager.debug E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 140)
05-09 14:22:23.966 14988-15020/io.github.muntashirakon.AppManager.debug E/PackageUtils: Could not retrieve package info list for user 0
    android.os.RemoteException: Transaction failed on small parcel; remote process probably died
        at io.github.muntashirakon.AppManager.servermanager.PackageManagerCompat.getInstalledPackages(PackageManagerCompat.java:93)
        at io.github.muntashirakon.AppManager.utils.PackageUtils.updateInstalledOrBackedUpApplications(PackageUtils.java:258)
        at io.github.muntashirakon.AppManager.utils.PackageUtils.getInstalledOrBackedUpApplicationsFromDb(PackageUtils.java:166)
        at io.github.muntashirakon.AppManager.main.MainViewModel.lambda$loadApplicationItems$2$MainViewModel(MainViewModel.java:266)
        at io.github.muntashirakon.AppManager.main.-$$Lambda$MainViewModel$GRBvAab9qfeXsa_mTxGQ7idH9GI.run(lambda)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by MPeti1** [comment]
with 'ADB over TCP' mode I get this:
```
05-09 14:27:20.266 11666-11689/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 140)
05-09 14:27:20.267 11666-11689/? E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    java.lang.RuntimeException: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.Parcel.writeException(Parcel.java:1520)
        at android.os.Binder.execTransact(Binder.java:459)
     Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:506)
        at io.github.muntashirakon.AppManager.ipc.AMService$IAMServiceImpl.transactRemote(AMService.java:147)
        at io.github.muntashirakon.AppManager.ipc.AMService$IAMServiceImpl.onTransact(AMService.java:121)
        at android.os.Binder.execTransact(Binder.java:453)
05-09 14:27:20.269 15680-15741/io.github.muntashirakon.AppManager.debug E/PackageUtils: Could not retrieve package info list for user 0
    android.os.RemoteException: com.google.android.gms not found.
        at io.github.muntashirakon.AppManager.servermanager.PackageManagerCompat.getInstalledPackages(PackageManagerCompat.java:93)
        at io.github.muntashirakon.AppManager.utils.PackageUtils.updateInstalledOrBackedUpApplications(PackageUtils.java:258)
        at io.github.muntashirakon.AppManager.utils.PackageUtils.getInstalledOrBackedUpApplicationsFromDb(PackageUtils.java:166)
        at io.github.muntashirakon.AppManager.main.MainViewModel.lambda$loadApplicationItems$2$MainViewModel(MainViewModel.java:266)
        at io.github.muntashirakon.AppManager.main.-$$Lambda$MainViewModel$GRBvAab9qfeXsa_mTxGQ7idH9GI.run(lambda)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by MPeti1** [comment]
with all 3 methods I also got this exception when opening the app:

```
05-09 14:27:16.123 15680-15680/io.github.muntashirakon.AppManager.debug E/BypassProvider: Unable to unseal hidden api access
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at org.chickenhook.restrictionbypass.RestrictionBypass.getDeclaredMethod(RestrictionBypass.java:18)
        at org.chickenhook.restrictionbypass.Unseal.unseal(Unseal.java:15)
        at org.chickenhook.restrictionbypass.BypassProvider.attachInfo(BypassProvider.java:51)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5257)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4808)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4748)
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
        at android.app.ActivityThread.handleBindApplication(<Xposed>)
        at android.app.ActivityThread.access$1700(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1436)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:5529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
     Caused by: java.lang.NoSuchMethodException: setHiddenApiExemptions [class [Ljava.lang.String;]
        at java.lang.Class.getMethod(Class.java:624)
        at java.lang.Class.getDeclaredMethod(Class.java:586)
        at java.lang.reflect.Method.invoke(Native Method) 
        at org.chickenhook.restrictionbypass.RestrictionBypass.getDeclaredMethod(RestrictionBypass.java:18) 
        at org.chickenhook.restrictionbypass.Unseal.unseal(Unseal.java:15) 
        at org.chickenhook.restrictionbypass.BypassProvider.attachInfo(BypassProvider.java:51) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:5257) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4808) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4748) 
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334) 
        at android.app.ActivityThread.handleBindApplication(<Xposed>) 
        at android.app.ActivityThread.access$1700(ActivityThread.java:153) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1436) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:5529) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102) 
```

**Comment by MuntashirAkon** [comment]
> I almost said it's also good to know which app is the offender and breaks the packagemanager, because at least I know which one to get rid of. Well, I'm not sure I can get rid of `com.google.android.gms` :D

This appears to be the first case. GMS must have a lot of app components which surpassed the parcel size limit. I wonder what would happen for [HMS Core](https://www.apkmirror.com/apk/huawei-internet-services/huawei-mobile-services/) which has an insane number of components.

**Comment by MuntashirAkon** [comment]
@MPeti1: Does the application list loads in the profile page like it used to be?

**Comment by MPeti1** [comment]
Yes, it does. It also has apps that were otherwise missing from the main list

**Comment by MuntashirAkon** [comment]
Check 819a346e.

**Comment by MPeti1** [comment]
It works this way! App list is loaded, and a lot of apps are there that wasn't before.
There are still a few similar exceptions, so I include them here:

<details>
<summary>Failed Binder transaction (no package name logged) (2 times)</summary>

```
05-09 16:35:56.199 11666-6373/? D/IPC: transact: uid=10146, descriptor=android.content.pm.IPackageManager, code=3
05-09 16:35:56.203 11666-6339/? D/IPC: transact: uid=10146, descriptor=android.content.pm.IPackageManager, code=3
05-09 16:35:56.206 11666-14797/? D/IPC: transact: uid=10146, descriptor=android.content.pm.IPackageManager, code=3
05-09 16:35:56.303 11666-14797/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 140)
05-09 16:35:56.306 11666-14797/? E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    java.lang.RuntimeException: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.Parcel.writeException(Parcel.java:1520)
        at android.os.Binder.execTransact(Binder.java:459)
     Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:506)
        at io.github.muntashirakon.AppManager.ipc.AMService$IAMServiceImpl.transactRemote(AMService.java:147)
        at io.github.muntashirakon.AppManager.ipc.AMService$IAMServiceImpl.onTransact(AMService.java:121)
        at android.os.Binder.execTransact(Binder.java:453)
05-09 16:35:56.307 11666-6377/? D/IPC: transact: uid=10146, descriptor=android.content.pm.IPackageManager, code=3
05-09 16:35:56.410 11666-11689/? D/IPC: transact: uid=10146, descriptor=android.content.pm.IPackageManager, code=3
05-09 16:35:56.473 11666-11686/? D/IPC: transact: uid=10146, descriptor=android.content.pm.IPackageManager, code=3

```

</details>

<details>
<summary>System.err: NPE (android.content.pm.ActivityInfo[] android.content.pm.PackageInfo.activities) (16 times)</summary>

```
05-09 16:35:59.355 7155-7233/io.github.muntashirakon.AppManager.debug W/System.err: java.lang.NullPointerException: Attempt to read from field 'android.content.pm.ActivityInfo[] android.content.pm.PackageInfo.activities' on a null object reference
05-09 16:35:59.355 7155-7233/io.github.muntashirakon.AppManager.debug W/System.err:     at io.github.muntashirakon.AppManager.servermanager.PackageManagerCompat.getPackageInfo(PackageManagerCompat.java:124)
05-09 16:35:59.355 7155-7233/io.github.muntashirakon.AppManager.debug W/System.err:     at io.github.muntashirakon.AppManager.utils.PackageUtils.collectComponentClassNames(PackageUtils.java:393)
05-09 16:35:59.355 7155-7233/io.github.muntashirakon.AppManager.debug W/System.err:     at io.github.muntashirakon.AppManager.rules.compontents.ComponentsBlocker.<init>(ComponentsBlocker.java:155)
05-09 16:35:59.355 7155-7233/io.github.muntashirakon.AppManager.debug W/System.err:     at io.github.muntashirakon.AppManager.rules.compontents.ComponentsBlocker.getInstance(ComponentsBlocker.java:140)
05-09 16:35:59.355 7155-7233/io.github.muntashirakon.AppManager.debug W/System.err:     at io.github.muntashirakon.AppManager.utils.PackageUtils.updateInstalledOrBackedUpApplications(PackageUtils.java:279)
05-09 16:35:59.355 7155-7233/io.github.muntashirakon.AppManager.debug W/System.err:     at io.github.muntashirakon.AppManager.utils.PackageUtils.lambda$getInstalledOrBackedUpApplicationsFromDb$0(PackageUtils.java:170)
05-09 16:35:59.356 7155-7233/io.github.muntashirakon.AppManager.debug W/System.err:     at io.github.muntashirakon.AppManager.utils.-$$Lambda$PackageUtils$FDXMpcfHZMTjLENDE7nHv1buIR0.run(lambda)
05-09 16:35:59.356 7155-7233/io.github.muntashirakon.AppManager.debug W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

</details>

**Comment by MuntashirAkon** [comment]
> ```
> java.lang.NullPointerException: Attempt to read from field 'android.content.pm.ActivityInfo[] android.content.pm.PackageInfo.activities' on a null object reference
> ```

This NPE can't be fixed because the number of activities are still too many to surpass the parcel size limit. I'll suppress that for now until I implement my own package parser as stated in https://github.com/MuntashirAkon/AppManager/issues/340#issuecomment-810854182.

**Comment by MuntashirAkon** [comment]
Fixed via c5fbf097, 09195323, 02766eec, 819a346e and 37342c23.

**Comment by MuntashirAkon** [comment]
@MPeti1 can you verify the number of apps against `pm list packages | grep package: | wc -l`? Filter only the installed apps in App Manager before doing so as it also contains uninstalled apps.

**Comment by bfabiszewski** [comment]
I reinstalled offending package and I confirm that DEBUG#1223 works fine.
The package doesn't cause PackageUtils exception any more.
The number of packages listed via `pm` corresponds to the number of installed apps listed in AM.
Thanks!

BTW I still see a bunch of JavaBinder exceptions when loading list, but it works fine.

```
05-09 17:40:01.596  2405  3255 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 132)
05-09 17:40:01.597  2405  3255 E JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
05-09 17:40:01.597  2405  3255 E JavaBinder: java.lang.RuntimeException: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
05-09 17:40:01.597  2405  3255 E JavaBinder: 	at android.os.Parcel.writeException(Parcel.java:1499)
05-09 17:40:01.597  2405  3255 E JavaBinder: 	at android.os.Binder.execTransact(Binder.java:464)
05-09 17:40:01.597  2405  3255 E JavaBinder: Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
05-09 17:40:01.597  2405  3255 E JavaBinder: 	at android.os.BinderProxy.transactNative(Native Method)
05-09 17:40:01.597  2405  3255 E JavaBinder: 	at android.os.BinderProxy.transact(Binder.java:511)
05-09 17:40:01.597  2405  3255 E JavaBinder: 	at io.github.muntashirakon.AppManager.ipc.AMService$IAMServiceImpl.transactRemote(AMService.java:147)
05-09 17:40:01.597  2405  3255 E JavaBinder: 	at io.github.muntashirakon.AppManager.ipc.AMService$IAMServiceImpl.onTransact(AMService.java:121)
05-09 17:40:01.597  2405  3255 E JavaBinder: 	at android.os.Binder.execTransact(Binder.java:458)
```

**Comment by MuntashirAkon** [comment]
> BTW I still see a bunch of JavaBinder exceptions when loading list

They indicate that certain packages couldn't be loaded using the standard method and an workaround was used.

**Comment by MuntashirAkon** [comment]
Anyway, I would be grateful if anybody run tests on HMS Core, both the main page and the app details page (to check if all the activities are loaded).

**Comment by bfabiszewski** [comment]
I installed HMS Core. Everything seems OK. It is listed on the main page. All the tabs in app details open. List of activities is really long.

**Comment by MuntashirAkon** [comment]
> I installed HMS Core. Everything seems OK. It is listed on the main page. All the tabs in app details open. List of activities is really long.

Thanks for testing. I use this app for smoke testing as it has the highest number of components I've seen.

**Comment by MPeti1** [comment]
> 
> 
> @MPeti1 can you verify the number of apps against `pm list packages | grep package: | wc -l`? Filter only the installed apps in App Manager before doing so as it also contains uninstalled apps.

Both the command and the selection counter (after pressing select all) shows 418, so it's working as intended. Thank you! :)
