### ISSUE TITLE
Android 12 Beta 1 crashes

### ISSUE THREAD

**Issue by nitanmarcel** [MuntashirAkon/AppManager#452]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

The app crashes on Android 12 Beta 1 when pressing any of the following tabs: User Permissions, Permissions,Uses Features.

**Device Info:**
App version: 2.6.0
App version code: 385
Android build version: 7333779
Android release version: 11
Android SDK version: 30
Android build ID: SPB1.210331.013
Device brand: google
Device manufacturer: Google
Device name: sunfish
Device model: Pixel 4a
Device product name: sunfish
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto

<details>
<summary>Logs</summary>

<pre>

java.lang.NoClassDefFoundError: io.github.muntashirakon.AppManager.appops.AppOpsManager
    at io.github.muntashirakon.AppManager.details.AppDetailsFragment.permAppOp(AppDetailsFragment.java:614)
    at io.github.muntashirakon.AppManager.details.AppDetailsFragment.access$1300(AppDetailsFragment.java:110)
    at io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.getPermissionsView(AppDetailsFragment.java:1438)
    at io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.onBindViewHolder(AppDetailsFragment.java:849)
    at io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.onBindViewHolder(AppDetailsFragment.java:618)
    at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
    at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
    at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
    at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
    at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
    at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
    at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at androidx.appcompat.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1655)
    at androidx.appcompat.widget.LinearLayoutCompat.layoutVertical(LinearLayoutCompat.java:1509)
    at androidx.appcompat.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1417)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:688)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
    at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
    at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2003)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:798)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3601)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3054)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2057)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8501)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1005)
    at android.view.Choreographer.doCallbacks(Choreographer.java:826)
    at android.view.Choreographer.doFrame(Choreographer.java:761)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7727)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
 Caused by: java.lang.ExceptionInInitializerError
   at io.github.muntashirakon.AppManager.appops.AppOpsManager.permissionToOpCode(AppOpsManager.java:1653)
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadAppOps(AppDetailsViewModel.java:1039)
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$l0EWUQ8pwSEwIOu4g2r5od7Q6Ks(Unknown Source:0)
   at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$l0EWUQ8pwSEwIOu4g2r5od7Q6Ks.run(Unknown Source:2)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
   at java.lang.Thread.run(Thread.java:920)
</pre>

</details>

**Comment by MuntashirAkon** [comment]
Should be fixed in 57cff29e

**Comment by nitanmarcel** [comment]
> 
> 
> Should be fixed in [57cff29](https://github.com/MuntashirAkon/AppManager/commit/57cff29e392968cf3f900cf36e093c571eb9609e)

Some apps show no permissions or apps ops and others still crash (I'm using the artefact from the latest CI build):

<details>
<summary>Logs</summary>

<pre>


java.lang.NoClassDefFoundError: io.github.muntashirakon.AppManager.appops.AppOpsManager
    at io.github.muntashirakon.AppManager.appops.AppOpsManager.permissionToOp(AppOpsManager.java:1734)
    at io.github.muntashirakon.AppManager.details.AppDetailsFragment.permAppOp(AppDetailsFragment.java:605)
    at io.github.muntashirakon.AppManager.details.AppDetailsFragment.access$1400(AppDetailsFragment.java:96)
    at io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.getPermissionsView(AppDetailsFragment.java:1419)
    at io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.onBindViewHolder(AppDetailsFragment.java:841)
    at io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.onBindViewHolder(AppDetailsFragment.java:609)
    at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
    at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
    at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
    at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
    at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
    at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
    at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at androidx.appcompat.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1655)
    at androidx.appcompat.widget.LinearLayoutCompat.layoutVertical(LinearLayoutCompat.java:1509)
    at androidx.appcompat.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1417)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:688)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
    at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
    at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2003)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:798)
    at android.view.View.layout(View.java:23055)
    at android.view.ViewGroup.layout(ViewGroup.java:6402)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3601)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3054)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2057)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8501)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1005)
    at android.view.Choreographer.doCallbacks(Choreographer.java:826)
    at android.view.Choreographer.doFrame(Choreographer.java:761)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7727)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
 Caused by: java.lang.ExceptionInInitializerError
   at io.github.muntashirakon.AppManager.appops.AppOpsManager.permissionToOpCode(AppOpsManager.java:1664)
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadUsesPermissions(AppDetailsViewModel.java:1206)
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$load$9$AppDetailsViewModel(AppDetailsViewModel.java:671)
   at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$llrumPmzrbtvwWMKkJUJipfWAtE.run(Unknown Source:4)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
   at java.lang.Thread.run(Thread.java:920)

Device Info:
App version: 2.7.0-1294-DEBUG
App version code: 386
Android build version: 7333779
Android release version: 11
Android SDK version: 30
Android build ID: SPB1.210331.013
Device brand: google
Device manufacturer: Google
Device name: sunfish
Device model: Pixel 4a
Device product name: sunfish
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto


</pre>

</details>

**Comment by nitanmarcel** [comment]
I can provide more logs if you need :)

**Comment by MuntashirAkon** [comment]
No idea why this issue is still present as I've made changes according to the publicly available source code. However, I've added a few changes in c11b39b7 to further debug the issue. Try it and see what happens.

**Comment by nitanmarcel** [comment]
> No idea why this issue is still present as I've made changes according to the publicly available source code. However, I've added a few changes in [c11b39b](https://github.com/MuntashirAkon/AppManager/commit/c11b39b78e7d4b2d5ea4f0eac06d2199fc494902) to further debug the issue. Try it and see what happens.

It's still crashing with the same error.

https://del.dog/aidingogis.txt

Also here's a logcat maybe it helps:

https://del.dog/phothudiqe.go

**Comment by MuntashirAkon** [comment]
> Also here's a logcat maybe it helps:
> 
> https://del.dog/phothudiqe.txt

Thanks, it surely did.

```
java.lang.IllegalStateException: sOpToSwitch length 105 should be 112
```

It's using 112 app ops but the available source code only has 105.

To fix this issue, you have to send me the **framework.jar** file located at `/system/framework/framework.jar` (it doesn't need root).

**Comment by MuntashirAkon** [comment]
Note that I cannot provide full support for Android 12 until the sources are released, I can only fix the reported issues.

**Comment by assembleDebug** [comment]
> To fix this issue, you have to send me the **framework.jar** file located at `/system/framework/framework.jar` (it doesn't need root).

Here is Framework.jar from Redfin (Pixel 5), Android 12, beta 1. If you need any other file, you can just look into the device dump. I am also running beta 1 on my poco m2 pro, but it's just a port. Saving a few MBs 😁

https://dumps.tadiphone.dev/dumps/google/redfin/-/raw/redfin-user-S-SPB1.210331.013-7333779-release-keys/system/system/framework/framework.jar?inline=false

**Comment by MuntashirAkon** [comment]
Fixed in da8ba4c1

**Comment by nitanmarcel** [comment]
> > To fix this issue, you have to send me the **framework.jar** file located at `/system/framework/framework.jar` (it doesn't need root).
> 
> Here is Framework.jar from Redfin (Pixel 5), Android 12, beta 1. If you need any other file, you can just look into the device dump. I am also running beta 1 on my poco m2 pro, but it's just a port. Saving a few MBs 😁
> 
> https://dumps.tadiphone.dev/dumps/google/redfin/-/raw/redfin-user-S-SPB1.210331.013-7333779-release-keys/system/system/framework/framework.jar?inline=false

You're here too lol

**Comment by nitanmarcel** [comment]
> Fixed in [da8ba4c](https://github.com/MuntashirAkon/AppManager/commit/da8ba4c19bfae2b37d77cd138b6467d2c3ef2d6f)

I can confirm it works now. Awesome

**Comment by nitanmarcel** [comment]
> Note that I cannot provide full support for Android 12 until the sources are released, I can only fix the reported issues.

Well everything else seem to work just fine. Idk if it's a bug but anyway it's not breaking anything useful: The app info section shows an infinite loading bar.

![Screenshot_20210525-111634](https://user-images.githubusercontent.com/41646249/119463724-b2355000-bd4a-11eb-8bec-6bb27c66dd96.png)

**Comment by MuntashirAkon** [comment]
> Well everything else seem to work just fine. Idk if it's a bug but anyway it's not breaking anything useful: The app info section shows an infinite loading bar.

Send some logs.

**Comment by MuntashirAkon** [comment]
> I can confirm it works now. Awesome

An issue is almost always fixable if the issue reporter provides all the resources that I need.

**Comment by assembleDebug** [comment]
> > Well everything else seem to work just fine. Idk if it's a bug but anyway it's not breaking anything useful: The app info section shows an infinite loading bar.
> 
> Send some logs.

https://del.dog/pegudickyp.go

Probably it's failing to read settings_ssaid.xml 
And just FYI, these XML files under /data/system/ aren't readable anymore with Android 12. They aren't plain text files, Google did some changes and the whole code looks obfuscated.

**Comment by MuntashirAkon** [comment]
> And just FYI, these XML files under /data/system/ aren't readable anymore with Android 12. They aren't plain text files, Google did some changes and the whole code looks obfuscated.

Send me the following APK file: `com.android.providers.settings`.

**Comment by nitanmarcel** [comment]
> > The app info section shows an infinite loading bar.
> 
> Should be fixed in [66209d2](https://github.com/MuntashirAkon/AppManager/commit/66209d200dcacf15020e3da2444e505c8ccbf20a)

Awesome. Also the scanner returns the same behavior:

https://paste.c-net.org/WhippleLamaze

**Comment by assembleDebug** [comment]
> > The app info section shows an infinite loading bar.
> 
> Should be fixed in [66209d2](https://github.com/MuntashirAkon/AppManager/commit/66209d200dcacf15020e3da2444e505c8ccbf20a)

Here it is - https://dumps.tadiphone.dev/dumps/google/redfin/-/blob/redfin-user-S-SPB1.210331.013-7333779-release-keys/system/system/priv-app/SettingsProvider/SettingsProvider.apk

And for some reason, debug builds are not installing on my phone now. It was installed earlier, but when I went to install latest debug from channel, it failed with an error "App not installed as package appears to be invalid". Here what it shows when I try to install manually with terminal.

![Screenshot_20210525-174513](https://user-images.githubusercontent.com/83750299/119496284-a1dd9f00-bd63-11eb-932c-3d7edc43735d.png)

**Comment by MuntashirAkon** [comment]
> And for some reason, debug builds are not installing on my phone now. It was installed earlier, but when I went to install latest debug from channel, it failed with an error "App not installed as package appears to be invalid". Here what it shows when I try to install manually with terminal.

It's probably part of some undocumented changes introduced in A12 or could simply be a bug. Don't expect a beta release to be stable. Anyway, a6b485fe should fix this.

>  https://dumps.tadiphone.dev/dumps/google/redfin/-/blob/redfin-user-S-SPB1.210331.013-7333779-release-keys/system/system/priv-app/SettingsProvider/SettingsProvider.apk

A lot of things have changed, it seems. Let's see if I can fix this by reverse engineering the APK.

**Comment by assembleDebug** [comment]
> It's probably part of some undocumented changes introduced in A12 or could simply be a bug. Don't expect a beta release to be stable. Anyway, [a6b485f](https://github.com/MuntashirAkon/AppManager/commit/a6b485feb72dd09bf14884584cf70cf630f47045) should fix this.
>

 Yesssss, it's fixed now, it installed fine with new debug build. Although, it got installed fine but it's showing some wierd behaviour, it's falling to non-root mode even when Superuser permission is granted to it. I am clean flashing Android 12 build, will install it again to see if the same behaviour persists. 

> A lot of things have changed, it seems. Let's see if I can fix this by reverse engineering the APK.
>
Yupp....

**Comment by MuntashirAkon** [comment]
> Although, it got installed fine but it's showing some wierd behaviour, it's falling to non-root mode even when Superuser permission is granted to it.

This appears to be an `app_process` related issue (happens to all apps that relies on it). I've faced similar issues on A11 and A10 (March/April patch). This usually gets fixed after restarting the device. I haven't found any pattern so far but it appears to be an Android frameworks bug. A12 issue could be different though.

**Comment by nitanmarcel** [comment]
> > > The app info section shows an infinite loading bar.
> > 
> > 
> > Should be fixed in [66209d2](https://github.com/MuntashirAkon/AppManager/commit/66209d200dcacf15020e3da2444e505c8ccbf20a)
> 
> Awesome. Also the scanner returns the same behavior:
> 
> https://paste.c-net.org/WhippleLamaze

This is how the scanner looks like @MuntashirAkon 

![Screenshot_20210525-175558](https://user-images.githubusercontent.com/41646249/119520068-9f3e7200-bd82-11eb-8b87-429195bd1bae.png)

**Comment by nitanmarcel** [comment]
Or nvm, it's still loading actually, waiting 1 min and everything filled up

**Comment by MuntashirAkon** [comment]
> Or nvm, it's still loading actually, waiting 1 min and everything filled up

Apps having a large number of classes take a lot of time. I'm currently working on an algorithm that uses multiple threads for searching class names. Hopefully, things will get faster when I'm done.

**Comment by nitanmarcel** [comment]
> > > > The app info section shows an infinite loading bar.
> > > 
> > > 
> > > Should be fixed in [66209d2](https://github.com/MuntashirAkon/AppManager/commit/66209d200dcacf15020e3da2444e505c8ccbf20a)
> > 
> > 
> > Awesome. Also the scanner returns the same behavior:
> > https://paste.c-net.org/WhippleLamaze
> 
> This is how the scanner looks like @MuntashirAkon
> 
> ![Screenshot_20210525-175558](https://user-images.githubusercontent.com/41646249/119520068-9f3e7200-bd82-11eb-8b87-429195bd1bae.png)

@MajeurAndroid  the current

> > Or nvm, it's still loading actually, waiting 1 min and everything filled up
> 
> Apps having a large number of classes take a lot of time. I'm currently working on an algorithm that uses multiple threads for searching class names. Hopefully, things will get faster when I'm done.

The current implementation doesn't allow you to instead of waiting for all the classes to be loaded after the task finishes to allow them to be appended one by one in the classes section as they load? Also a cache of the classes that is available until the app closes or the respective app is reinstalled/updated I think it would be a good idea. Because it seems that the app loads the classes each time you open the Scanner view and I don't think the classes will changed unless a new update changes them

**Comment by MuntashirAkon** [comment]
> The current implementation doesn't allow you to instead of waiting for all the classes to be loaded after the task finishes to allow them to be appended one by one in the classes section as they load?

Current way of loading class names is actually a modified version of ClassyShark3xodus' implementation, which doesn't work very well, i.e. apart from being very slow, it doesn't analyse Java byte code, therefore, it misses out a lot of important classes. This will be replaced in future. We'll also add scanning network signatures.

> Also a cache of the classes that is available until the app closes or the respective app is reinstalled/updated I think it would be a good idea. Because it seems that the app loads the classes each time you open the Scanner view and I don't think the classes will changed unless a new update changes them

It's generally unexpected that a user would scan the same APK more than once or twice. According to the users that I've interacted with, they mostly use this feature for scanning external APKs. So, I didn't think it would be appropriate to fill user storage with a bunch of useless class names.

**Comment by MuntashirAkon** [comment]
> Here it is - https://dumps.tadiphone.dev/dumps/google/redfin/-/blob/redfin-user-S-SPB1.210331.013-7333779-release-keys/system/system/priv-app/SettingsProvider/SettingsProvider.apk

They have introduced a new kind of `XmlPullParser` called `TypedXmlPullParser`, presumably to store and retrieve XML files in a faster way (storing XML as binary is nothing new to Java and Android developers). Since the source of A12 is yet to be released under Apache-2.0, `TypedXmlPullParser` is still under a proprietary license, therefore, I cannot copy the file (even if I can access it by reverse engineering the **framework.jar**). So, I'm disabling the feature for A12 until they finally release the source.
