### ISSUE TITLE
Displaying and/or changing SSAID is not working on Android 12

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/AppManager#457]
Due to recent changes in how settings files are stored, `settings_ssaid.xml` has become unreadable to App Manager. This issue will be fixed as soon as Google releases the sources of Android 12.

**Comment by MuntashirAkon** [comment]
Fixed in 11b7e486

**Comment by huyz-git** [comment]
I still cannot see the SSAID option on Android 12.
I tested in the AVD in android studio. With API31 (S, 12) or API32 (Sv2, 12L) image, the SSAID option is not showed, but with API30 (R, 11) image it showed.
On both AVD, AM worked in root mode.
![Screenshot_20220707_182204](https://user-images.githubusercontent.com/22879638/177751778-fd7c306c-2b50-468c-9696-5ef185b064a5.png)
![Screenshot_20220707_182154](https://user-images.githubusercontent.com/22879638/177751802-0eeaa7ea-b2aa-4819-9667-8f407af3c1b8.png)

**Comment by f12c** [comment]
Same here.
I cannot see the SSAID option on Pixel 6 A12.

**Comment by MuntashirAkon** [comment]
Fixed in 1f0dd312942822d5b31253f2e6f02fbfb6d7dd22
