### ISSUE TITLE
App manager crashes when the back up to be made contains too many files

### ISSUE THREAD

**Issue by hhaio** [MuntashirAkon/AppManager#470]
- [x] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'App manager'
2. Click on 'multi select user apps'
3. Click on backup/restore
4. Initiate backing up with default options
5. After some time the AM crashes 

**Crash logs**
```
java.lang.AssertionError: Binder ProxyMap has too many entries: 23722 (total), 23722 (uncleared), 19591 (uncleared after GC). BinderProxy leak?
    at android.os.BinderProxy$ProxyMap.set(BinderProxy.java:228)
    at android.os.BinderProxy.getInstance(BinderProxy.java:415)
    at android.os.Parcel.nativeReadStrongBinder(Native Method)
    at android.os.Parcel.readStrongBinder(Parcel.java:2162)
    at io.github.muntashirakon.AppManager.IAMService$Stub$Proxy.getFile(IAMService.java:261)
    at io.github.muntashirakon.io.ProxyFile.getRemoteFile(ProxyFile.java:301)
    at io.github.muntashirakon.io.ProxyFile.<init>(ProxyFile.java:57)
    at io.github.muntashirakon.io.ProxyFile.listFiles(ProxyFile.java:230)
    at io.github.muntashirakon.io.ProxyFile.listFiles(ProxyFile.java:36)
    at io.github.muntashirakon.AppManager.utils.DigestUtils.gatherFiles(DigestUtils.java:176)
    at io.github.muntashirakon.AppManager.utils.DigestUtils.gatherFiles(DigestUtils.java:181)
    at io.github.muntashirakon.AppManager.utils.DigestUtils.gatherFiles(DigestUtils.java:181)
    at io.github.muntashirakon.AppManager.utils.DigestUtils.gatherFiles(DigestUtils.java:181)
    at io.github.muntashirakon.AppManager.utils.DigestUtils.gatherFiles(DigestUtils.java:181)
    at io.github.muntashirakon.AppManager.utils.DigestUtils.getHexDigest(DigestUtils.java:70)
    at io.github.muntashirakon.AppManager.backup.BackupOp.lambda$backupData$0$BackupOp(BackupOp.java:246)
    at io.github.muntashirakon.AppManager.backup.-$$Lambda$BackupOp$OACxlh4YwzLYzk3LfLESE6sIDtI.run(Unknown Source:2)
    at java.lang.Thread.run(Thread.java:919)
```

**Device Info**
App version: 2.6.0
App version code: 385
Android build version: 52
Android release version: 10
Android SDK version: 29
Android build ID: lineage_davinci-userdebug 10 QQ3A.200805.001 52 release-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: davinci
Device model: Mi 9T
Device product name: lineage_davinci
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto

**Comment by hhaio** [comment]
Now that the alpha 01 has released, does this mean the issue has been fixed?

**Comment by MuntashirAkon** [comment]
> Now that the alpha 01 has released, does this mean the issue has been fixed?

The sidebar says it belongs to alpha02. This issue is very complicated and requires a completely new design which I have been working on for several months but I still cannot provide an ETA.

**Comment by hhaio** [comment]
Okay, waiting eagerly.
Thanks

**Comment by MuntashirAkon** [comment]
After a thorough review, it now appears to me that this issue can be fixed by reducing the number of remote object creation by the use of primitive data structures and/or non-Parcelable objects. This crash happens because a lot of file attributes has to be read within a fixed amount of time causing the BinderProxy map to reach the maximum size (if the amount of files is very high). Suffice to say that a major revision is needed for this and will be part of alpha03 (instead of alpha02).

However, it should reduce the number of crashes in 336fd9e9543f4cf4d55b202500dab9e13ac7133f (which is due for alpha02).

**Comment by MuntashirAkon** [comment]
Should be fixed in 900354d1b9499cba737d91e9fb6c8b86715ccf58
