### ISSUE TITLE
Miui appops in Android 11 don't support "per-uid" set op mode?

### ISSUE THREAD

**Issue by d4rkk3y** [MuntashirAkon/AppManager#497]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
 I can not change mode of custom app ops of miui. Can we use per-package set op mode for miui app ops?

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any App details
2. Click on "app ops"
3. Scroll down and change mode any app op of miui (10000+)
4. Toast message: "Could not enable the requested app op" or "This app op can not be disable"

**Expected behavior**
Can change the mode of custom app op of miui.

**Screenshots**
![image](https://user-images.githubusercontent.com/43563783/124111992-0e9b3600-da94-11eb-9c7e-ca81603219a9.png)

**Crash logs**

**Device info**
 - Device: Black shark 3
 - OS Version: [Android 11]
 - App Manager Version: [2.6.2]
 - Mode: wireless debugging

**Additional context**
MIUI optimiztion is turn off.

**Comment by MuntashirAkon** [comment]
So, it only works for package only, and not UID?

**Comment by d4rkk3y** [comment]
Yes. I tested it in my device.

**Comment by d4rkk3y** [comment]
I read here https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/app/AppOps.md
They said: "Do not use setMode and setUidMode for the same app-op. Due to the way the internal storage for the mode works this can lead to very confusing behavior. If this ever happened by accident this needs to be cleaned up for any affected user as the app-op mode is retained over reboot."
But in your app code I see 
![image](https://user-images.githubusercontent.com/43563783/124115037-8323a400-da97-11eb-9e0a-e94db422fe02.png)
Mean if android version is M, O, P, Q it will use setMode and setUidMode for same app-op. I didn't fully understand what they said above but is it true that we should not use setMode and setUidMode for the same app-op?

**Comment by MuntashirAkon** [comment]
> I didn't fully understand what they said above but is it true that we should not use setMode and setUidMode for the same app-op?

It means that they didn't test the feature enough to ensure its safety. They attempted to fix it by removing the package mode altogether, which still didn't fix most of the existing issues.

Since you are using Android 11 (where package mode isn't supported), my guess is that Xiaomi is still using the old package mode, at least, for their own app ops.

App ops has gotten more messy in Android 11 (and could be more in 12) and I don't know where their going with this hybrid permission system which hasn't been tested properly (and my issue on the Google Issue Tracker never got fixed).

**Comment by MuntashirAkon** [comment]
Fixed in 7bd04166. Have you ever tried the same in Android 10 or earlier? Did they work back in 10? If so, I might have to switch to uid mode for them as uid mode has higher priorities than package mode.

**Comment by d4rkk3y** [comment]
I remember that this problem still happended when I haven't updated to 11 yet. Because the toast message error clearly told me the reason(readonly appop or depend on other) so I didn't report.

**Comment by MuntashirAkon** [comment]
> I remember that this problem still happended when I haven't updated to 11 yet. Because the toast message error clearly told me the reason(readonly appop or depend on other) so I didn't report.

So, it means this fix should fix them too. I wonder why MIUI handles their own app ops differently. Anyway, thanks for the report.
